## PLAYER
PLAYER_SIZE = 75
PLAYER_SHEET = "Assests/img/CharacterSheet.png"
PLAYER_SPEED = 5
PLAYER_HEALTH = 5
PLAYER_SHOOT_SPEED = 35
## CARROT
CARROT_SIZE = 75
CARROT_SHEET = "Assests/img/carrotEnemy.png"
CARROT_SPEED = 6
CARROT_SHOOT_SPEED = 0
CARROT_HEALTH = 3

# GAME
IFRAMES = 10